// Reexport the double macro from our derive crate
pub use double_derive::double;

/// An empty Dummy type. Each trait generated by the [`double`] macro will be implemented for this
/// type.
pub struct Dummy;
