// Reexport the double macro from our derive crate
pub use double_derive::dummies;

/// An empty Dummy type. Each trait generated by the [`dummies`] macro will be implemented for this
/// type.
///
/// ```no_run
/// use double_trait::{dummies, Dummy};
///
/// #[dummies]
/// trait OrgTrait {
///     fn answer(&self) -> i32;
/// }
///
/// OrgTrait::answer(&Dummy); // Compiles, but raises panic with `unimplemented!()`
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Dummy;
